# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!


target 'HomeWork' do
  pod 'Alamofire', '~> 4.0'
  pod 'PKHUD', '~> 5.0'
  pod 'SwiftyJSON'

end


target 'HomeWorkTests' do
    pod 'Alamofire', '~> 4.0'
    pod 'PKHUD', '~> 5.0'
    pod 'SwiftyJSON'
end

